// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfDLB1itYeu8W4nCzIlpp-5B12Ao4xyDY',
    appId: '1:304143906019:web:cfa660bd8092ad1ebb81d6',
    messagingSenderId: '304143906019',
    projectId: 'quick-broker-906f6',
    authDomain: 'quick-broker-906f6.firebaseapp.com',
    storageBucket: 'quick-broker-906f6.appspot.com',
    measurementId: 'G-37RZ1NETJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwe_FxMDxpwAlp6rfz5V6pXwex1272J4A',
    appId: '1:754373477027:android:72b97f1775d32e9f973516',
    messagingSenderId: '754373477027',
    projectId: 'quickbroker-fbaf4',
    storageBucket: 'quickbroker-fbaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvXNkaUUQFbo5LCdWnIoh3pJQ3Am5nNs',
    appId: '1:754373477027:ios:204799ca94fc80bf973516',
    messagingSenderId: '754373477027',
    projectId: 'quickbroker-fbaf4',
    storageBucket: 'quickbroker-fbaf4.appspot.com',
    iosClientId:
        '754373477027-keb64eeqigdefefsgo2nj065t092sbh4.apps.googleusercontent.com',
    iosBundleId: 'com.quickbroker.app.quikbroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfDLB1itYeu8W4nCzIlpp-5B12Ao4xyDY',
    appId: '1:304143906019:web:84db48a5d164d8a9bb81d6',
    messagingSenderId: '304143906019',
    projectId: 'quick-broker-906f6',
    authDomain: 'quick-broker-906f6.firebaseapp.com',
    storageBucket: 'quick-broker-906f6.appspot.com',
    measurementId: 'G-TXPVFB17KD',
  );

}